name: Compile Chapel Examples

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: agirish/chapel:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Chapel Examples
        run: |
          # Assuming the Chapel code is in a file named "hello.chpl"
          chpl hello.chpl
          ./hello
