name: Compile Chapel Examples

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-run-chapel:
    uses: agirish/chapel-workflows/.github/workflows/compile-with-chapel.yml@main
    with:
      file_name: hello.chpl
